### ISSUE TITLE
Cookie based login will be deprecated soon. Does this library support OAuth?

### ISSUE THREAD

**Issue by clearitout** [jReddit/jReddit#114] opened 2015-02-10 03:03 UTC
https://www.reddit.com/r/redditdev/comments/2ujhkr/important_api_licensing_terms_clarified/

**Comment by sfat** [comment] 2015-02-17 18:00
Hey @clearitout. The library doesn't support OAuth at the moment. (Did you actually went through all reddit wrappers on github to ask this question? :) )

**Comment by sfat** [comment] 2015-06-23 07:44
closing this as duplicate of #132

**Closed by sfat** 2015-06-23 07:44 UTC
Labels: enhancement
